#!/bin/bash

# driver [GLOB]
#
# Runs executable files (matching GLOB) under the `case` subdirectory,
# in alpha order.
#
# If $PRESERVE_TEMP_DIRS is set, temporary directories created by test
# cases are preserved; otherwise they are deleted.

HERE=${0%/*}

source $HERE/lib.sh

_PASS=()
_FAIL=()

main() {
    cd "$HERE/case"
    local name_glob='*'
    [[ -n "$1" ]] && name_glob="$1"
    cases=$(find . -type f -perm /111 -name "$name_glob" | sort)
    if [[ -z "$cases" ]]; then
        echo "No test cases found! Something is wrong!"
        exit 1
    fi

    echo "Will run test cases:"
    echo "$cases" | ${SED?} 's,^./,  ,'

    for test_case_executable in $cases; do
        test_case_name=${test_case_executable#./}
        echo
        hr
        echo "Running test case $test_case_name"
        hr
        # Invoke
        $test_case_executable
        RC=$?
        hr
        if [[ $RC -eq 0 ]]; then
            colorprint ${GREEN} PASS
            _PASS+=($test_case_name)
        else
            colorprint ${RED} "FAIL with RC=$RC"
            _FAIL+=($test_case_name)
        fi
        echo
    done

    hr
    colorprint ${GREEN} "PASS: ${#_PASS[@]}"
    /bin/echo -n "  "
    colorprint ${GREEN} ${_PASS[@]} | ${SED?} 's/ /\n  /g'
    colorprint ${RED} "FAIL: ${#_FAIL[@]}"
    /bin/echo -n "  "
    colorprint ${RED} ${_FAIL[@]} | ${SED?} 's/ /\n  /g'
    hr
    if [[ ${#_FAIL[@]} -ne 0 ]]; then
        exit 1
    fi
    exit 0
}

main "$@"
