#!/bin/bash

# Runs executable files under the `case` subdirectory, in alpha order.
#
# If $PRESERVE_TEMP_DIRS is set, temporary directories created by test
# cases are preserved; otherwise they are deleted.

HERE=${0%/*}

source $HERE/lib.sh

_PASS=()
_FAIL=()

main() {
    cd "$HERE/case"
    # TODO: Add support for running just certain cases
    cases=$(find . -type f -perm -u+x | sort)
    if [[ -z "$cases" ]]; then
        echo "No test cases found! Something is wrong!"
        exit 1
    fi

    echo "Will run test cases:"
    echo "$cases"

    for test_case_executable in $cases; do
        echo
        hr
        echo "Running test case $test_case_executable"
        hr
        # Invoke
        $test_case_executable
        RC=$?
        hr
        if [[ $RC -eq 0 ]]; then
            echo PASS
            _PASS+=($test_case_executable)
        else
            echo "FAIL with RC=$RC"
            _FAIL+=($test_case_executable)
        fi
        echo
    done

    hr
    echo "PASS: ${#_PASS[@]}"
    echo -n "  "
    echo ${_PASS[@]} | sed 's/ /\n  /g'
    echo "FAIL: ${#_FAIL[@]}"
    echo -n "  "
    echo ${_FAIL[@]} | sed 's/ /\n  /g'
    hr
    if [[ ${#_FAIL[@]} -ne 0 ]]; then
        exit 1
    fi
    exit 0
}

main
