#!/bin/bash -e

REPO_ROOT=$(git rev-parse --show-toplevel)

source $REPO_ROOT/test/lib.sh

repo=$(empty_repo)
add_cleanup $repo

bootstrap_repo $repo

cd $repo

make update-boilerplate

check_update $repo 01-no-convention

if [ $? -ne 0 ] ; then
	exit $?
fi

add_convention $repo test/test-base-convention
make update-boilerplate

check_update $repo 01-with-convention

exit $?
