#!/bin/bash -e

REPO_ROOT=$(git rev-parse --show-toplevel)

source $REPO_ROOT/test/lib.sh

repo=$(empty_repo)
add_cleanup $repo

bootstrap_repo $repo

cd $repo

# TODO: test REPO_NAME detection by setting an appropriately-formatted
# git remote
export REPO_NAME=${0##*/}

make update_boilerplate

check_update $repo 01_no_convention

if [ $? -ne 0 ] ; then
	exit $?
fi

add_convention $repo test/test_base_convention
make update_boilerplate

check_update $repo 01_with_convention

exit $?
