version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/boilerplate"
      - "/config"
    labels:
      - "area/dependency"
      - "ok-to-test"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "redhat-services-prod/openshift/boilerplate"
        # don't upgrade boilerplate via these means
      - dependency-name: "openshift4/ose-operator-registry"
        # don't upgrade ose-operator-registry via these means
