#!/usr/bin/env bash

set -e

REPO_ROOT=$(git rev-parse --show-toplevel)

source $REPO_ROOT/test/lib.sh

# This is funky.
# For security reasons, the freeze-check script is hardcoded to use the
# real boilerplate repo as its source of truth for determining whether
# anything has been changed. We need to override that in order to test
# the current boilerplate commit. But of course, overriding the
# freeze-check script will, by design, cause freeze-check to fail. So we
# have to create a new clone of boilerplate, from the current commit,
# then override that hardcoded variable in a *new* commit, then start
# the freeze check from there.
prep_freeze_check() {
    orig_repo=$REPO_ROOT
    export REPO_ROOT=$(mktemp -d -t boilerplate-freeze-check-XXXXXXXX)
    add_cleanup $REPO_ROOT
    export BOILERPLATE_GIT_REPO=$REPO_ROOT
    git clone $orig_repo $REPO_ROOT
    ${SED?} -i 's,^BOILERPLATE_GIT_REPO=.*$,BOILERPLATE_GIT_REPO='$REPO_ROOT',' $REPO_ROOT/boilerplate/_lib/freeze-check
    git -C $REPO_ROOT config user.name "Test Boilerplate" >&2
    git -C $REPO_ROOT config user.email "test@example.com" >&2
    git -C $REPO_ROOT commit -am "Override BOILERPLATE_GIT_REPO for freeze-check"
}

echo "Testing freeze-check"
repo=$(empty_repo)
add_cleanup $repo
# There's nothing special about file-generate -- we could as easily use
# an empty repo -- but this is convenient.
test_project="file-generate"

convention=openshift/golang-osd-operator
prep_freeze_check
bootstrap_project $repo ${test_project} ${convention}
cd $repo

echo "'make boilerplate-freeze-check' should succeed directly after bootstrap."
make boilerplate-freeze-check

cur_branch=$(current_branch $repo)

echo "Expect failure when changing boilerplate-owned files"
# Validate for a file in the convention *and* for a file that the
# convention's `update` copies out into the main part of the repo.
for f in boilerplate/${convention}/codecov.sh .codecov.yml; do
  # Make dirty, and expect validation to fail via `isclean`.
  /bin/echo "# foo" >> $f
  expect_failure "Can't validate boilerplate in a dirty repository. Please commit your changes and try again." make boilerplate-freeze-check
  # Commit the change, and expect validation to fail via freeze-check.
  git checkout -b dirty
  git commit -a -m dirty
  expect_failure "Your boilerplate is dirty!" make boilerplate-freeze-check
  # Get back to the original commit
  git reset --hard HEAD
  git checkout $cur_branch
  git branch -D dirty
done

# Now let's make sure a non-bp-owned file doesn't fail
# Make dirty
/bin/echo "# foo" >> Makefile
expect_failure "Can't validate boilerplate in a dirty repository. Please commit your changes and try again." make boilerplate-freeze-check
git checkout -b clean
git commit -a -m clean
make boilerplate-freeze-check
