#!/usr/bin/env bash

set -e

REPO_ROOT=$(git rev-parse --show-toplevel)

source $REPO_ROOT/test/lib.sh

echo "Testing image tags"
repo=$(empty_repo)
add_cleanup $repo
test_project="file-generate"

convention=openshift/golang-osd-operator
bootstrap_project $repo ${test_project} ${convention}
cd $repo

# The convention's `update` replaces the FROM line in the Dockerfile.
cat -<<EOF >$LOG_DIR/expected-Dockerfile
FROM quay.io/app-sre/boilerplate:$LATEST_IMAGE_TAG AS builder

ENV OPERATOR=/usr/local/bin/file-generate \\
    USER_UID=1001 \\
    USER_NAME=file-generate

# install operator binary
COPY build/_output/bin/file-generate \${OPERATOR}

COPY build/bin /usr/local/bin
RUN  /usr/local/bin/user_setup

ENTRYPOINT ["/usr/local/bin/entrypoint"]

USER \${USER_UID}
EOF

diff $LOG_DIR/expected-Dockerfile build/Dockerfile

# The convention's `update` fills in the .ci-operator.yaml.
# NOTE: Change this when publishing a new image tag.
cat -<<EOF >$LOG_DIR/expected-.ci-operator.yaml
build_root_image:
  name: boilerplate
  namespace: openshift
  tag: $LATEST_IMAGE_TAG
EOF

diff $LOG_DIR/expected-.ci-operator.yaml .ci-operator.yaml
