#!/usr/bin/env bash

set -e

REPO_ROOT=$(git rev-parse --show-toplevel)

source $REPO_ROOT/test/lib.sh

echo "Testing CRD v1 generation"

repo=$(empty_repo)
add_cleanup $repo
test_project="file-generate"

bootstrap_project $repo ${test_project} openshift/golang-osd-operator
cd $repo
BOILERPLATE_IN_CI=1 make boilerplate-update

make op-generate

diff deploy/crds/mygroup.operators.coreos.com_testkinds.yaml expected/mygroup.operators.coreos.com_testkinds.yaml || err "CRD generation didn't work properly."
diff api/v1beta1/zz_generated.deepcopy.go expected/zz_generated.deepcopy.go || err "controller-gen code generation didn't work properly."
