// THIS FILE IS GENERATED BY BOILERPLATE. DO NOT EDIT.
//go:build osde2e

package osde2etests

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/go-logr/logr"
	operatorsv1alpha1 "github.com/operator-framework/api/pkg/operators/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/util/wait"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
)

const (
	precheckPollInterval = 5 * time.Second
	precheckTimeout      = 10 * time.Minute
)

var (
	csvGVR = schema.GroupVersionResource{
		Group:    "operators.coreos.com",
		Version:  "v1alpha1",
		Resource: "clusterserviceversions",
	}
	clusterPackageGVR = schema.GroupVersionResource{
		Group:    "package-operator.run",
		Version:  "v1alpha1",
		Resource: "clusterpackages",
	}
)

func runOperatorPreChecks(ctx context.Context, logger logr.Logger, restConfig *rest.Config, operatorName, operatorNamespace, expectedVersion string) error {
	restConfig.QPS = 50
	restConfig.Burst = 100

	dynClient, err := dynamic.NewForConfig(restConfig)
	if err != nil {
		return fmt.Errorf("failed to create dynamic client: %w", err)
	}

	kubeClient, err := kubernetes.NewForConfig(restConfig)
	if err != nil {
		return fmt.Errorf("failed to create kubernetes client: %w", err)
	}

	logger.Info("running operator pre-checks", "operator", operatorName, "expectedVersion", expectedVersion)

	var lastStatus string

	err = wait.PollUntilContextTimeout(ctx, precheckPollInterval, precheckTimeout, false, func(ctx context.Context) (bool, error) {
		if _, err := kubeClient.CoreV1().Namespaces().Get(ctx, operatorNamespace, metav1.GetOptions{}); err != nil {
			lastStatus = fmt.Sprintf("namespace %s not found", operatorNamespace)
			return false, nil
		}

		if expectedVersion != "" && expectedVersion != "latest" {
			found, pkoReady, pkoStatus := checkOperatorPKO(ctx, logger, dynClient, operatorName, expectedVersion)
			if found {
				if !pkoReady {
					lastStatus = pkoStatus
					return false, nil
				}
			} else {
				olmReady, olmStatus := checkOperatorOLM(ctx, logger, dynClient, operatorNamespace, operatorName, expectedVersion)
				if !olmReady {
					lastStatus = olmStatus
					return false, nil
				}
			}
		}

		ready, status := checkDeploymentsReady(ctx, kubeClient, operatorNamespace)
		if !ready {
			lastStatus = status
			return false, nil
		}

		logger.Info("operator pre-checks passed", "operator", operatorName, "namespace", operatorNamespace)
		return true, nil
	})
	if err != nil {
		return fmt.Errorf("operator %q did not become ready within %v (last status: %s): %w",
			operatorName, precheckTimeout, lastStatus, err)
	}

	return nil
}

func checkOperatorPKO(ctx context.Context, logger logr.Logger, dynClient dynamic.Interface, operatorName, expectedTag string) (bool, bool, string) {
	result, err := dynClient.Resource(clusterPackageGVR).List(ctx, metav1.ListOptions{})
	if err != nil {
		logger.Info("could not list ClusterPackages, PKO may not be installed", "error", err)
		return false, false, ""
	}

	for _, item := range result.Items {
		name := item.GetName()
		if !strings.Contains(strings.ToLower(name), strings.ToLower(operatorName)) {
			continue
		}

		spec, _ := item.Object["spec"].(map[string]interface{})
		specImage, _ := spec["image"].(string)
		logger.Info("found ClusterPackage", "name", name, "image", specImage)

		_, pkgTag := extractOperatorVersionFromImage(specImage)
		if !versionMatches(pkgTag, expectedTag) {
			return true, false, fmt.Sprintf("ClusterPackage %s has version %q, want %q", name, pkgTag, expectedTag)
		}

		status, _ := item.Object["status"].(map[string]interface{})
		conditions, _ := status["conditions"].([]interface{})

		for _, c := range conditions {
			cond, ok := c.(map[string]interface{})
			if !ok {
				continue
			}
			condType, _ := cond["type"].(string)
			condStatus, _ := cond["status"].(string)
			condMessage, _ := cond["message"].(string)
			if condType == "Available" {
				if condStatus == "True" {
					logger.Info("ClusterPackage version matched and available", "name", name, "tag", pkgTag)
					return true, true, ""
				}
				return true, false, fmt.Sprintf("ClusterPackage %s Available=%s: %s", name, condStatus, condMessage)
			}
		}

		return true, false, fmt.Sprintf("ClusterPackage %s has no Available condition", name)
	}

	return false, false, ""
}

func checkOperatorOLM(ctx context.Context, logger logr.Logger, dynClient dynamic.Interface, namespace, operatorName, expectedTag string) (bool, string) {
	result, err := dynClient.Resource(csvGVR).Namespace(namespace).List(ctx, metav1.ListOptions{})
	if err != nil {
		return false, fmt.Sprintf("failed to list CSVs in %s: %v", namespace, err)
	}

	var lastCSV string
	for _, item := range result.Items {
		csvName := item.GetName()
		if !strings.Contains(strings.ToLower(csvName), strings.ToLower(operatorName)) {
			continue
		}
		lastCSV = csvName

		status, _ := item.Object["status"].(map[string]interface{})
		phase, _ := status["phase"].(string)
		if csvMatchesVersion(csvName, expectedTag) && phase == string(operatorsv1alpha1.CSVPhaseSucceeded) {
			logger.Info("CSV version matched and succeeded", "csv", csvName)
			return true, ""
		}
	}

	if lastCSV != "" {
		return false, fmt.Sprintf("CSV %s found but version/phase doesn't match", lastCSV)
	}
	return false, fmt.Sprintf("no CSV found for operator %s in %s", operatorName, namespace)
}

func checkDeploymentsReady(ctx context.Context, kubeClient kubernetes.Interface, namespace string) (bool, string) {
	deployments, err := kubeClient.AppsV1().Deployments(namespace).List(ctx, metav1.ListOptions{})
	if err != nil {
		return false, fmt.Sprintf("failed to list deployments in %s: %v", namespace, err)
	}

	if len(deployments.Items) == 0 {
		return true, ""
	}

	for _, d := range deployments.Items {
		desired := int32(1)
		if d.Spec.Replicas != nil {
			desired = *d.Spec.Replicas
		}
		if d.Status.AvailableReplicas < desired {
			return false, fmt.Sprintf("deployment %s/%s: %d/%d replicas available",
				namespace, d.Name, d.Status.AvailableReplicas, desired)
		}
	}

	return true, ""
}

func extractOperatorVersionFromImage(image string) (string, string) {
	if image == "" {
		return "", ""
	}

	var tag string
	if idx := strings.LastIndex(image, ":"); idx != -1 {
		tag = image[idx+1:]
		image = image[:idx]
	}

	if idx := strings.LastIndex(image, "/"); idx != -1 {
		image = image[idx+1:]
	}

	suffixes := []string{"-e2e", "-test", "-tests", "-harness"}
	for _, suffix := range suffixes {
		if strings.HasSuffix(image, suffix) {
			image = strings.TrimSuffix(image, suffix)
			break
		}
	}

	return image, tag
}

func extractCommitFromTag(tag string) string {
	if tag == "" {
		return ""
	}

	parts := strings.Split(tag, "-")
	for _, part := range parts {
		if strings.HasPrefix(part, "g") && len(part) >= 7 {
			return part[1:]
		}
	}

	return tag
}

func csvMatchesVersion(csvName, expectedTag string) bool {
	if csvName == "" || expectedTag == "" {
		return false
	}

	if containsVersionBoundary(csvName, expectedTag) {
		return true
	}

	commit := extractCommitFromTag(expectedTag)
	if commit != expectedTag && commit != "" {
		return strings.Contains(csvName, commit)
	}

	return false
}

// containsVersionBoundary checks that s contains version as a whole token,
// not as a substring of a longer version (e.g. v0.1 must not match v0.10.0).
func containsVersionBoundary(s, version string) bool {
	idx := strings.Index(s, version)
	if idx == -1 {
		return false
	}
	end := idx + len(version)
	if end == len(s) {
		return true
	}
	next := s[end]
	return next == '.' || next == '-' || next == '_'
}

func versionMatches(actual, expected string) bool {
	if actual == "" || expected == "" {
		return false
	}
	if actual == expected {
		return true
	}
	actualCommit := extractCommitFromTag(actual)
	expectedCommit := extractCommitFromTag(expected)
	if actualCommit != actual && expectedCommit != expected {
		return actualCommit == expectedCommit
	}
	return false
}
