#!/bin/bash -e

source $STANDARDS_ROOT/_lib/common.sh

# No PRE
[[ "$1" == "PRE" ]] && exit 0

# Expect POST
[[ "$1" == "POST" ]] || err "Got a parameter I don't understand: '$1'. Did the infrastructure change?"

echo "Updating the main repo's Makefile to include rollup includes.mk as the first thing it does"
TMPD=$(mktemp -d)
trap "rm -fr $TMPD" EXIT
cat <<EOF> $TMPD/Makefile
# Injected by standards/make/update
include standards/make/includes.mk
EOF
# Remove any existing imports from standards (but leave others in place)
sed -e '/\bstandards\/make\b/d' $REPO_ROOT/Makefile >> $TMPD/Makefile
cp $TMPD/Makefile $REPO_ROOT/Makefile
