#!/usr/bin/env bash

set -e

# Functions in common are currently unneeded
# source $CONVENTION_ROOT/_lib/common.sh

# No PRE
[[ "$1" == "PRE" ]] && exit 0

# Expect POST
[[ "$1" == "POST" ]] || err "Got a parameter I don't understand: '$1'. Did the infrastructure change?"

cat <<EOF

=====================
THINGS YOU NEED TO DO
=====================
- Make sure the following line is in your base Makefile:

include boilerplate/generated-includes.mk

- Remove any other 'include' lines, unless they're for things truly
  unique to your repository. (Otherwise, consider proposing them to
  boilerplate.)

- Delete any obsolete files you're no longer including.

- Have a Dockerfile in ./build/Dockerfile and define IMAGE_NAME for it.
  Others container images can be specified with ADDITIONAL_IMAGE_SPECS

=====================

EOF
