FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_1.22
COPY config/build_image.sh /build_image.sh
COPY LICENSE /licenses/.
RUN /build_image.sh && rm /build_image.sh
# test do not merge
