#!/usr/bin/env bash

set -e

REPO_ROOT=$(git rev-parse --show-toplevel)

source $REPO_ROOT/test/lib.sh

repo=$(empty_repo)
add_cleanup $repo

bootstrap_repo $repo

cd $repo

BOILERPLATE_IN_CI=1 make boilerplate-update

check_update $repo 01-no-convention

if [ $? -ne 0 ] ; then
    exit $?
fi

# So the next update starts "clean"
./boilerplate/_lib/boilerplate-commit

add_convention $repo test/test-base-convention
BOILERPLATE_IN_CI=1 make boilerplate-update

check_update $repo 01-with-convention

exit $?
