#!/usr/bin/env bash

echo "Validate that a nonexistent convention causes update to fail."

REPO_ROOT=$(git rev-parse --show-toplevel)

source $REPO_ROOT/test/lib.sh

repo=$(empty_repo)
add_cleanup $repo

bootstrap_repo $repo

cd $repo
# Subscribe to a "convention" that doesn't exist upstream
/bin/echo "bogus/convention" >> boilerplate/update.cfg

LOG=$LOG_DIR/${0##*/}.log

# A little cheat so we can get the RC from `make`
BOILERPLATE_IN_CI=1 make boilerplate-update >$LOG 2>&1
rc=$?
cat $LOG

if [[ $rc -eq 0 ]]; then
    echo "Expected update to fail!"
    exit 1
fi
expected="Invalid convention directory: 'bogus/convention'"
if ! grep -q "$expected" $LOG; then
    echo "Expected update output to contain:"
    echo "  $expected"
    echo "...but it didn't. See above."
    exit 1
fi

exit 0
