#!/bin/bash -e

cat <<EOF
Tests updating from the current boilerplate master to the current
commit, and then reverting to the master.
EOF

# TODO: This test requires an active network connection to access the
# actual boilerplate github repository. We should label it as such and
# make a granny switch to disable all such tests.

HERE=${0%/*}

REPO_ROOT=$(git rev-parse --show-toplevel)

source $REPO_ROOT/test/lib.sh

# Hack: some checks will fail if master is at an earlier tag. Other
# tests validate the proper setting of this variable.
export SKIP_IMAGE_TAG_CHECK=1

repo=$(empty_repo)
add_cleanup $repo

bootstrap_repo $repo

cd $repo

boilerplate_master=$(new_boilerplate_clone)

override_boilerplate_repo $boilerplate_master || exit $?

add_convention $repo test/test-base-convention
make boilerplate-update || exit $?
check_update $repo 04-check-after-init || exit $?

reset_boilerplate_repo

make boilerplate-update || exit $?
check_update $repo 04-check-new-version-update || exit $?

override_boilerplate_repo $boilerplate_master || exit $?

make boilerplate-update || exit $?
check_update $repo 04-check-new-version-update || exit $?
