#!/usr/bin/env bash

# WARNING: THIS FILE IS MANAGED IN THE 'standardize' REPO AND COPIED TO OTHER REPOSITORIES.
# ONLY EDIT THIS FILE FROM WITHIN THE 'standardize' REPOSITORY.
# 
# TO OPT OUT OF UPDATES, SEE THE README.

# This script updates itself, and then re-execs itself if it has
# changed. This is in case updates to standards rely on updates to this
# script.

set -e

# Were we re-exec'd?
if [ "$1" ]; then
  OUT=$1
  # Let's make sure this was really a re-exec and not some other
  # weirdness.
  if ! [[ -d "$OUT" ]] || ! diff -q "$0" "$OUT/standardize/standards/update"; then
    echo "Something went wrong! I was invoked with '$OUT'!"
    exit 2
  fi
else
  OUT="$(mktemp -d)"
  git clone git@github.com:2uasimojo/standardize.git "${OUT}"
  echo "Updating the update script."
  cp "${OUT}/standardize/standards/update" "$0"
  echo "Reinvoking..."
  echo ""
  exec "$0" "$OUT"
  # unreached
fi

trap "rm -fr $OUT" EXIT

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
# The directory in which this script lives is the STANDARDS_ROOT. Export
# this for individual `update` scripts.
export STANDARDS_ROOT=$DIR

# Allow this to be overridden by the environment, in case some bizarre
# repo doesn't have an `origin` remote.
if [ -z "$REPO_NAME" ]; then
  # This is a tad ambitious, but it should usually work.
  export REPO_NAME=$(git remote get-url origin | sed 's,.*/,,; s/\.git$//')
fi

export REPO_ROOT=$(git rev-parse --show-toplevel)

CONFIG_FILE="${DIR}/update.cfg"
README="https://github.com/2uasimojo/standardize/blob/master/README.md"

if [ ! -f "$CONFIG_FILE" ]; then
  echo "$CONFIG_FILE not found."
  echo "This file is required in order to select which features to include." 
  echo "See $README for more details."
  exit 1
fi

while read directory junk; do
  # Skip comment lines (which can have leading whitespace)
  if [[ "$directory" == '#'* ]]; then
    continue
  fi
  # Skip blank or whitespace-only lines
  if [[ "$directory" == "" ]]; then
    continue
  fi
  # Lines like
  #    valid/path  other_junk
  # are not acceptable, unless `other_junk` is a comment
  if [[ "$junk" != "" ]] && [[ "$junk" != '#'* ]]; then
    echo "Invalid config! Only one directory is allowed per line. Found '$junk'"
    exit 1
  fi

  dir_path="${OUT}/standards/${directory}"
  # Make sure the directory exists
  if ! [[ -d "$dir_path" ]]; then
    echo "Invalid standards directory: '$directory'"
    exit 1
  fi

  echo "***********************************************************************************"
  echo "$directory is configured in update.cfg."
  echo "-----------------------------------------------------------------------------------"
  echo "syncing files from source."
  rm -rf "${DIR}/${directory}"
  mkdir -p $(dirname "${DIR}/${directory}")
  cp -r "$dir_path" "${DIR}/${directory}"
  if [ -f "${DIR}/${directory}/update" ]; then
    echo "executing ${DIR}/${directory}/update"
    "${DIR}/${directory}/update"
  fi
  echo "***********************************************************************************"
  echo ""
done < "$CONFIG_FILE"
