#!/bin/bash -e

source $CONVENTION_ROOT/_lib/common.sh

# No PRE
[[ "$1" == "PRE" ]] && exit 0

# Expect POST
[[ "$1" == "POST" ]] || err "Got a parameter I don't understand: '$1'. Did the infrastructure change?"

echo "Updating the main repo's Makefile to include rollup includes.mk as the first thing it does"
TMPD=$(mktemp -d)
trap "rm -fr $TMPD" EXIT
cat <<EOF> $TMPD/Makefile
# Injected by boilerplate/make/update
include boilerplate/make/includes.mk
EOF
# Remove any existing imports from boilerplate (but leave others in place)
sed -e '/\bboilerplate\/make\b/d' $REPO_ROOT/Makefile >> $TMPD/Makefile
cp $TMPD/Makefile $REPO_ROOT/Makefile
